FROM rust:1.88-bullseye AS builder

WORKDIR /app
COPY . .

RUN cargo build --release

FROM debian:bullseye-slim
WORKDIR /app

COPY --from=builder /app/target/release/qortex-rust-backend /app/backend

CMD ["./backend"]